steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/my-cloudservice:$COMMIT_SHA", "."]
  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/my-cloudservice:$COMMIT_SHA"]
  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "my-cloudservice"
      - "--image"
      - "gcr.io/$PROJECT_ID/my-cloudservice:$COMMIT_SHA"
      - "--region"
      - "northamerica-norteast1"
      - "--platform"
      - "managed"
images:
  - "gcr.io/$PROJECT_ID/my-cloudservice:$COMMIT_SHA"
